builder.py
blocknetdx/exrproxy-env pull request #147
Opened 2022-02-14 18:01 UTC by pom11

QA

- [ ] `python3 builder.py --yaml` - check if passing a custom input yaml is processed as expected
- [ ] `python3 builder.py --nochecks` - check if docker checks are bypassed
- [ ] `python3 builder.py --noenv` - check if creating .env is bypassed
- [ ] `python3 builder.py --deploy` - check if the stack is deployed correctly 
- [ ] `python3 builder.py --prune` - check if pruning docker works as expected
- [ ] `python3 builder.py` - check if a stack is created as expected

Feel free to request builder.py questions changes.

2022-02-14 18:10 UTC, ConanMishler requested changes
```
? Prune/remove all docker networks?  Yes
? Prune/remove all docker volumes?  Yes
? Prune/remove all docker images?  Yes
```
I suggest we change these three questions to be as follows:
```
? Prune/remove all unused docker networks [Y/n]?
? Prune/remove all unused docker volumes (does not delete synced blockchain data) [Y/n]?
? Prune/remove all unused docker images [Y/n]?
```
 I think adding the word, "`unused`" to each of these 3 questions will help the snode op understand that it's generally safe and good to prune.
Also, adding "(does not delete synced blockchain data)" to the question on pruning volumes will address the concern @walkjivefly had, and many other snode ops will likely have as well.
Also, in terms of default answers for those questions, I think the Linux convention is to add "`[Y/n]`" to the end of the question. This indicates that the capitalized Y will be chosen if the user just presses "Enter."

2022-02-14 18:22 UTC, walkjivefly commented on autobuild/sources.yaml
> +  image: avaplatform/avalanchego:v1.7.4
Latest is v1.7.5.

2022-02-19 21:42 UTC, ConanMishler requested changes
The first thing I want to say is, "WELL DONE!!!"  This is a very cool tool which is going to make it much simpler for SNode Ops to configure & deploy their SNodes. Bravo!

That said, I have a few change requests... ;-)

- [ ]  1. The more I think about it, the more I feel we should really take the time to write a simple version of `builder.sh` as a bash wrapper for `builder.py`. It's just really user-unfriendly to ask the user to exit from `builder.py`, then run `./installdocker.sh`, then remember to run `builder.py` again after docker is installed. If it were difficult to fix this user-unfriendlyness, that would be one thing, but it's really not difficult to fix. This first version of `builder.sh` only needs to do the following:

	1. Install python3 and pip3
	2. Run `pip3 install -r requirements.txt`
	3. Check if docker and docker-compose are installed; offer to install them if they're not already installed.
	4. Check if a `docker` Linux group already exists; create `docker` group if it doesn't already 	exist.
	5. Check if the user is a member of the `docker` Linux group; if not, add the user to the docker group.
	6. If docker and docker-compose are installed, run `builder.py`, forwarding to it whatever params were passed to `builder.sh` (help message of `builder.sh` should be similar, if not identical to that of `builder.py`.)
	7. Running `deploy.sh` from within Python with
	`stream = os.popen('./deploy.sh');print(stream.read())` causes thousands of lines to be printed to the screen, which is inconvenient for anyone wanting to scroll back on their screen. Since we're gonna make a `builder.sh` bash wrapper anyway, let's run `./deploy.sh` from within the bash script (if they pass `--deploy`).
Future versions of `docker.sh` can also install `git` and clone the `exrproxy-env` repo, but we don't need to do all that in this first version.

- [x]  2. I Can't approve/merge this until new docker images for `exrproxy` and `eth-payment-processor` are pushed to docker hub. Without those, this PR will break things. (Of course, references to these two images in `sources.yaml` will also need to be updated once the new images have been pushed to Docker Hub.)

- [x]  3. I gave these 4 answers to these 4 questions:
```
? Press enter for 35USD tier1 amount or type a new price:  10
? Press enter for 200USD tier2 amount or type a new price:  20
? Press enter for 20% aBlock discount or type a new discount:  30
? Press enter for 20% aaBlock discount or type a new discount:  0
```
The result was an input yaml like this was generated:
```
  - name: PAYMENT
    payment_tier1: 10
    payment_tier2: 10
    discount_ablock: 10
    discount_aablock: 10
```
Apparently, all the user-entered payment amounts and discount amounts are being ignored.

- [x]  4. To make it clear what values the user should enter, the text of these 4 queries should be:
```
? Press enter for 35USD tier1 amount or type a new USD price for tier1:
? Press enter for 200USD tier2 amount or type a new USD price for tier2:
? Press enter for 20% aBLOCK discount or type a new discount (e.g. 15 for 15% aBLOCK discount):
? Press enter for 20% aaBLOCK discount or type a new discount (e.g. 15 for 15% aaBLOCK discount):
```
Without these clarifications the user may not know the units of the values they are entering (i.e. USD & Percentage).
I will also give a detailed example in the docs of how all these values work together to determine the amount charged to the Hydra/XQuery client.

- [x]  5. The text of these 3 queries:
```
? Prune/remove all docker networks?  (Y/n)
? Prune/remove all docker volumes?  (Y/n)
? Prune/remove all docker images?  (Y/n)
```
should be updated to read:
```
? Prune/remove all unused docker networks?  (Y/n)
? Prune/remove all unused docker volumes (will not delete synced blockchain data)?  (Y/n)
? Prune/remove all unused docker images?  (Y/n)
```
This should help remove any unnecessary fear of pruning docker objects.

- [x]  6. Regarding these 2 queries:
```
? Do you wish to configure HYDRA?
? Do you wish to configure XQUERY?
```
Let's change these 2 queries to:
```
? Do you wish to support HYDRA?
? Do you wish to support XQUERY?
```
Once they choose to support Hydra/XQuery, then the config queries for each will automatically be presented to the user.

- [x]  7. Regarding these 2 user queries:
```
? Select which indices you want for ETH:  [UNISWAP]
? Select which indices you want for AVAX:  [PANGOLIN]
```
I'm not sure "indices" is the best word to use. Maybe "graphs" would be better? Or maybe something like this:
```
? Select which graphs/indices you want for ETH:  [UNISWAP]
? Select which graphs/indices you want for AVAX:  [PANGOLIN]
```

- [x]  8. This AVAX entry in `autobuild/sources.yaml` needs to be bumped to v1.7.5:
```
- name: AVAX
  type: evm_chain 
  image: avaplatform/avalanchego:v1.7.4
  data_mount_dir: /snode
```

- [x]  9. Help message for `--noenv` currently says:
```
--noenv          uninit env vars checks
```
Let's change that help message to something like:
```
--noenv          Don't check if `.env` file exists (only for advanced users)
```
The only use I can think of for this `--noenv` option would be if a user wants to set the necessary ENV variables in their own special way, not using the default `.env` file, before calling `docker-compose -f "docker-compose.yml" up -d --build`. Only advanced users may want to do such things.

- [x]  10. Please add a `--new-env` option to set all environment variables to new values (as per new user input). I realized the user could simply delete the `.env` file before running `.builder.py`, but I feel it'll be more user-friendly to have a command line option which does this for them.

- [x]  11. `./builder.py` fails to bring down (i.e. stop and remove) running docker containers. Maybe this is more easily done in the `builder.sh` bash wrapper script?

- [x]  12. `installdocker.sh` does *not* install `docker-compose` properly. `installdocker()` bash function worked previously as part of `deploy.sh`, but that was using `DOCKER_COMPOSE_VERSION="1.26.2"`.
The `installdocker.sh` script uses `DOCKER_COMPOSE_VERSION="2.2.3"`, and this seems to break `docker-compose` installation.

- [ ]  13. The following files should *not* be stored on Github since they are all generated locally (or no longer useful). Storing them on Github causes conflicts and/or overwriting of local versions on git pull/merge. All these files should be deleted from exrproxy-env repo:
```
.env
scripts/start-{snode,xrproxy,xrproxy-gethext}.sh
scripts/entrypoints/start-{bit,lite}coin.sh
```

- [ ]  14. There are no options to create testSNODE, TNODE and testTNODE in place of SNODE in the input yaml. See steps 14, 15 & 16 of these docs for descriptions of testSNODE, TNODE and testTNODE: https://docs.blocknet.co/service-nodes/setup/#prepare-to-deploy-service-node

- [ ]  15. Regarding these user queries:
```
? Press enter to use ETH internally or type external IP Address:
? Press enter to use AVAX internally or type external IP Address:
```
It would be nice if `builder.py` could be made to remember any external IPs provided for ETH or AVAX, then present those external IPs as the default values the next time `builder.py` is called. The reason is, if an snode op specifies an external IP for ETH or AVAX once, they are very likely to want to use the same external IP the next time they run `builder.py`. (Note: This feature may not be super high priority, and could probably wait till a later release. But if it's easy...)

- [ ]  16. `autobuild/sources.yaml` lacks comments about HW resources required to deploy each of the services listed. Until `builder.py` is smart enough to track those HW requirements (including RAM and # of CPU cores required, not just disk space required), those per-service HW requirement comments from the old `alldaemons.yaml` should be included in `autobuild/sources.yaml`. This will help the SNode Op determine which combination of services their machine can support [...]

2022-02-23 02:14 UTC, ConanMishler commented
I was just playing a bit with the latest version on this `dev-autobuilder-pom` branch and I noticed a couple of simple things:
1. The 2 files `scripts/start-snode.sh` and `scripts/start-xrproxy.sh` need to be made executable by user after they are generated by `builder.py`
2. `discount_aablock: 20` still needs to be changed to `discount_aablock: 0` in `autobuild/sources.yaml`
You probably had this second one on your list bc I mentioned it in Discord, but I thought I should also leave a comment about it here in the PR just to make sure it doesn't slip through the cracks. ;-)

2022-02-25 01:36 UTC, ConanMishler commented
I just realized something. Linux does not recognize a newly added Linux group (like `docker`) or a user's membership in that group until the user logs out, then logs back in.  As such, let's **not** try to do these two steps in `builder.sh`:
```
Check if a docker Linux group already exists; create docker group if it doesn't already exist.
Check if the user is a member of the docker Linux group; if not, add the user to the docker group.
```
Instead, I'll just leave instructions in the guide for taking these steps manually (then logging out & back in).

2022-02-25 03:11 UTC, ConanMishler commented
I'd like to change my request #16 slightly. Instead of adding comments about HW requirements to each resource entry in `autobuild/sources.yaml`, add a new field in each entry which gives a very brief summary of the HW Reqs for that resource. For Example:
```
- name: ETH
  type: evm_chain
  image: ethereum/client-go:latest 
  geth_data_mount_dir: /snode 
  HW_Reqs: "10+ TB NVMe SSD storage, 16 GB RAM, 6+ CPU"

- name: AVAX
  type: evm_chain 
  image: avaplatform/avalanchego:v1.7.5
  data_mount_dir: /snode
  HW_Reqs: "400+ GB SSD storage, 16 GB RAM, 6+ CPU"

- name: BTC 
  type: chain
  image: blocknetdx/bitcoin:v0.20.0
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "500+ GB SSD storage"

- name: DASH 
  type: chain
  image: blocknetdx/dash:v0.17.0.3
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "35+ GB SSD storage"

- name: DGB 
  type: chain
  image: blocknetdx/digibyte:v7.17.2
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "30+ GB SSD storage, 5+ GB RAM"

- name: LTC 
  type: chain
  image: blocknetdx/litecoin:v0.18.1
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "75+ GB SSD storage"

- name: PIVX 
  type: chain
  image: blocknetdx/pivx:v5.3.2
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "23+ GB SSD storage"

- name: SYS 
  type: chain
  image: blocknetdx/syscoin4:v4.3.0
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "4+ GB SSD storage"

- name: LBC 
  type: chain
  image: blocknetdx/lbrycredits:v0.17.4.6
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "150+ GB SSD storage"

- name: MUE 
  type: chain
  image: blocknetdx/monetaryunit:v2.2.0
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "6+ GB SSD storage"

- name: PHR 
  type: chain
  image: blocknetdx/phore:v1.8.0
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "7+ GB SSD storage"

- name: RVN 
  type: chain
  image: blocknetdx/ravencoin:v4.3.2.1
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "27+ GB SSD storage"

- name: GBX 
  type: chain
  image: blocknetdx/gobyte:v0.16.2.1
  config_mount_dir: /snode
  data_mount_dir: /snode
  HW_Reqs: "3+ GB SSD storage"
```
Then display the HW_Reqs value next to the resource when the user is being queried whether they want to deploy that resource. It will be *so much* more user friendly than asking the user to reference `autobuild/sources.yaml` to find out each resource's HW requirements. I realize you have plans to make the `awesome-builder` fully aware of the actual current HW requirements for each entry, but I think adding these static HW_Reqs text fields would be a good temporary way to make the `awesome-builder` quite user-friendly.

2022-03-01 20:45 UTC, ConanMishler commented
I remember looking through the builder.py code and finding where the code "kills" any already running docker containers which are going to be re-launched by builder.py. I suggest, rather than "killing" the containers, we should "stop" the containers, then "remove" them. The reason is that "stopping" the containers sends SIGTERM, and therefore has a higher probability of allowing the containers to stop gracefully, whereas "killing" the containers sends SIGKILL, which immediately kills it with no 10 second graceful shutdown period. Note, neither "stopping" nor "killing" the containers causes them to be removed, and they need to be removed after being stopped (`docker rm <container`) so no error is generated saying, "container name already exists" when the stack is redeployed.

2022-03-01 22:55 UTC, ConanMishler commented
I just happened to notice all files I requested to be deleted from `exrproxy-env` repo in point 13 above have been deleted *except one*: `.env`. That file is generated locally by `builder.py`, so I don't see any reason to keep `.env` in the `exrproxy-env` repo.

2022-03-03 18:01 UTC, ConanMishler commented
When I run `builder.py` on VPS4, it automatically finds my public IP, but it chops off the last digit when it prints it. It prints this:
```
PUBLIC_IP=194.163.143.6
```
But it should print this:
```
PUBLIC_IP=194.163.143.68
```

2022-03-04 22:15 UTC, ConanMishler commented
Disclaimer: The following issue is not directly related to the `awesome-builder`, but I think the easiest way to fix this issue will be to make a few minor mods to `builder.py`, `autobuild/app.py` and `autobuild/templates/dockercompose.j2`.

I just made an important discovery WRT running `avalanchego` within a docker container. I kept noticing that my `avalanchego` instance on VPS4 was chronically *unhealthy* due to too much time being taken to process blocks. I noticed in the avax logs that the Public IP for the avax node was being set to the IP of the avax docker container, not the external/public IP of VPS4. After researching this a bit in Avalanche Discord, it looks like an avax node broadcasts its registered "Public IP" to its peers, and if it broadcasts a Public IP which doesn't match its actual public IP, then its peers will lower its quality rating (or something like that). So, avax nodes running inside a docker container need to set their Public IP using the `--public-ip=PUBLIC_IP` command line param. As such, the Public IP of the server, which is already fetched by `blocker.py`, needs to be added as a command line param for avax like this:
```
 avax:
    command:
      - --http-host=0.0.0.0
      - --index-enabled
      - --db-dir=/data
      - --public-ip=PUBLIC_IP
```
Note, my two avax nodes (on VPS2 & VPS4) have been *healthy* since I added this `--public-ip=PUBLIC_IP` param. Also, I'm able to restart my avax node on VPS2 in just 15 minutes! 🥳 (I haven't tried to restart avax on VPS4 yet.)

2022-03-05 19:48 UTC, ConanMishler commented
Ok, one last suggestion. This may not be high priority, but at some point it will be nice if the `awesome-builder` can inform the user that all blockchain data will be stored in `/snode` directory by default. Then give the user the option to change that for all blockchains and/or change it for each blockchain individually. For example, some snode ops supporting GETH will likely want to mount the geth_data_mount_dir on a specially directory where there is lots of space.

It may not be essential to have this feature in the first release because I can describe in the docs how the user can use `builder` to generate an input `.yaml`, then edit that input `.yaml` w/ a new `data_mount_dir`, then run builder again, but this time pass the *--yaml* param to reference the edited `.yaml`.

2022-03-07 19:54 UTC, ConanMishler commented
- [ ]   Just realized one more (simple) feature is needed:
The old `autobuild/app.py` accepted a parameter `--branchpath BRANCHPATH`.
`builder.sh` needs to accept this same param and forward it to the `app.py` code so `app.py` can do the right thing with it.

2022-03-07 21:46 UTC, pom11 commented
> 

i m removing them from repo and init them dynamically at startup of builder.py

2022-03-08 00:51 UTC, pom11 commented
>  Just realized one more (simple) feature is needed:
The old autobuild/app.py accepted a parameter --branchpath BRANCHPATH.
builder.sh needs to accept this same param and forward it to the app.py code so app.py can do the right thing with it.

i would leave that hardcode for now as is a superadvanced requirement and solely blocknet team will edit that. users will need to update builder.py to fetch the branch

2022-03-08 01:01 UTC, pom11 commented
did a push without:
- 1
- 14
- 16
- 23
- 24

2022-03-08 01:27 UTC, ConanMishler commented
> > Just realized one more (simple) feature is needed:
> > The old autobuild/app.py accepted a parameter --branchpath BRANCHPATH.
> > builder.sh needs to accept this same param and forward it to the app.py code so app.py can do the right thing with it.
> 
> i would leave that hardcoded for now as is a superadvanced requirement and solely blocknet team will edit that. users will need to update builder.py to fetch the branch

If it were difficult to add the `--branchpath BRANCHPATH` param, I would agree with you. However, please consider the following points:
1. The `--branchpath BRANCHPATH` feature was added to `app.py` by @walkjivefly. He's probably not going to appreciate that it was removed without consulting him in the "new and improved" `builder.sh`.
2. It's really not difficult to add that feature to `builder.sh` (and `builder.py`).
3. The goal is to allow *anyone* to list a new coin, or update and test new configs of a coin - not just Blocknet team members. It is *very user-unfriendly* to require users to edit `builder.py` when they want to deploy an SNode with custom configs.
4. Whatever we release has to be documented (by me). If we release `builder.sh` *without* the `--branchpath BRANCHPATH` feature, I have to first document how to manually edit `builder.py` with a custom URL for configs, then change the documents later on to describe how to pass the `--branchpath BRANCHPATH` param to `builder.sh` once that feature has been added. I've already written the `builder.sh` documents on the assumption the `--branchpath BRANCHPATH` feature will be there, so I'll have to change what I've written if it's not there.

2022-03-08 13:01 UTC, ConanMishler commented
An image of v1.7.6 of `avalanchego` has just been released. I've tested it on VPS4 and it seems to work fine. However, instead of referencing v1.7.6 explicitly, I'm referencing it with the `latest` tag, like this:
```
image: avaplatform/avalanchego:latest
```
- [ ]  I suggest we update the AVAX entry in `autobuild/sources.yaml` to reference the avalanchego image w/ the `latest` tag, so it will always point to the *latest* version.

2022-03-08 16:30 UTC, ConanMishler commented
> Do you wish to support FREE access to HYDRA? [Y/n]

Nice idea to offer this option, but should't it default to *NO*? And what exactly is "FREE" access to Hydra? Does that mean they get access to ETH and AVAX data without paying anything? Or does it mean they don't have to pay extra for Hydra access if they've already paid for XQuery access? I think the latter case is already the way it works, no?

2022-03-08 16:43 UTC, ConanMishler commented
- [ ] 28.
> ? Prune/remove all docker networks?  (Y/n)

Minor, but it'll be better if this says:
```
? Prune/remove all unused docker networks?  (Y/n)
```

2022-03-08 18:15 UTC, ConanMishler commented
I completely uninstalled docker & docker-compose on VPS2. Then I ran `installdocker.sh`, and it failed failed:
```
Reading package lists... Done
W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:55 and /etc/apt/sources.list.d/docker.list:1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  docker-ce-rootless-extras docker-scan-plugin pigz slirp4netns
Suggested packages:
  aufs-tools cgroupfs-mount | cgroup-lite
The following NEW packages will be installed:
  docker-ce docker-ce-cli docker-ce-rootless-extras docker-scan-plugin pigz slirp4netns
The following packages will be upgraded:
  containerd.io
1 upgraded, 6 newly installed, 0 to remove and 121 not upgraded.
Need to get 23.7 MB/97.2 MB of archives.
After this operation, 299 MB of additional disk space will be used.
Get:1 https://download.docker.com/linux/ubuntu focal/stable amd64 containerd.io amd64 1.4.13-1 [23.7 MB]
Fetched 23.7 MB in 1s (45.0 MB/s)       
Selecting previously unselected package pigz.
(Reading database ... 133736 files and directories currently installed.)
Preparing to unpack .../0-pigz_2.4-1_amd64.deb ...
Unpacking pigz (2.4-1) ...
Preparing to unpack .../1-containerd.io_1.4.13-1_amd64.deb ...
Unpacking containerd.io (1.4.13-1) over (1.4.12-1) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../2-docker-ce-cli_5%3a20.10.12~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce-cli (5:20.10.12~3-0~ubuntu-focal) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../3-docker-ce_5%3a20.10.12~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce (5:20.10.12~3-0~ubuntu-focal) ...
Selecting previously unselected package docker-ce-rootless-extras.
Preparing to unpack .../4-docker-ce-rootless-extras_5%3a20.10.12~3-0~ubuntu-focal_amd64.deb ...
Unpacking docker-ce-rootless-extras (5:20.10.12~3-0~ubuntu-focal) ...
Selecting previously unselected package docker-scan-plugin.
Preparing to unpack .../5-docker-scan-plugin_0.12.0~ubuntu-focal_amd64.deb ...
Unpacking docker-scan-plugin (0.12.0~ubuntu-focal) ...
Selecting previously unselected package slirp4netns.
Preparing to unpack .../6-slirp4netns_0.4.3-1_amd64.deb ...
Unpacking slirp4netns (0.4.3-1) ...
Setting up slirp4netns (0.4.3-1) ...
Setting up docker-scan-plugin (0.12.0~ubuntu-focal) ...
Setting up containerd.io (1.4.13-1) ...
Installing new version of config file /etc/containerd/config.toml ...
Setting up docker-ce-cli (5:20.10.12~3-0~ubuntu-focal) ...
Setting up pigz (2.4-1) ...
Setting up docker-ce-rootless-extras (5:20.10.12~3-0~ubuntu-focal) ...
Setting up docker-ce (5:20.10.12~3-0~ubuntu-focal) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2022-03-08 19:06:33 CET; 6ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 1453635 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 1453635 (code=exited, status=1/FAILURE)

Mar 08 19:06:33 vmi698280.contaboserver.net systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 08 19:06:33 vmi698280.contaboserver.net systemd[1]: Failed to start Docker Application Container Engine.
Mar 08 19:06:35 vmi698280.contaboserver.net systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
Mar 08 19:06:35 vmi698280.contaboserver.net systemd[1]: Stopped Docker Application Container Engine.
Mar 08 19:06:35 vmi698280.contaboserver.net systemd[1]: Starting Docker Application Container Engine...
Mar 08 19:06:35 vmi698280.contaboserver.net dockerd[1453656]: time="2022-03-08T19:06:35.374228396+01:00" level=info msg="Starting up"
Mar 08 19:06:35 vmi698280.contaboserver.net dockerd[1453656]: failed to load listeners: no sockets found via socket activation: make sure the service was started by systemd
Mar 08 19:06:35 vmi698280.contaboserver.net systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 19:06:35 vmi698280.contaboserver.net systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 08 19:06:35 vmi698280.contaboserver.net systemd[1]: Failed to start Docker Application Container Engine.
Mar 08 19:06:37 vmi698280.contaboserver.net systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
Mar 08 19:06:37 vmi698280.contaboserver.net systemd[1]: Stopped Docker Application Container Engine.
Mar 08 19:06:37 vmi698280.contaboserver.net systemd[1]: Starting Docker Application Container Engine...
Mar 08 19:06:37 vmi698280.contaboserver.net dockerd[1453666]: time="2022-03-08T19:06:37.629653201+01:00" level=info msg="Starting up"
Mar 08 19:06:37 vmi698280.contaboserver.net dockerd[1453666]: failed to load listeners: no sockets found via socket activation: make sure the service was started by systemd
Mar 08 19:06:37 vmi698280.contaboserver.net systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 19:06:37 vmi698280.contaboserver.net systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 08 19:06:37 vmi698280.contaboserver.net systemd[1]: Failed to start Docker Application Container Engine.
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3.13) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python3-attr python3-cached [...]

2022-03-09 22:45 UTC, ConanMishler commented
- [ ] 27. I just discovered an issue WRT stopping docker containers. When `builder.py` discovers `exrproxy-env` containers are already running, it offers to stop them, and then stops them if the user replies in the affirmative. Then it offers:

```
? Prune/remove all stopped docker containers? (Y/n)
```
If the user replies, "yes" to pruning stopped containers, networks, etc, then everything works fine on the "happy path." However, if the user replies, "no." the containers remain stopped, but not removed. Later on, when the user goes to deploy the stack, he gets errors like these:
```
ERROR: for exrproxy-env_postgresql_1  Cannot start service postgresql: network 8f6b9679c89842010f2fc9cf0cf3689f6e106097af26aabb987b8ea36eaf6cca not found
```
Even if the user had not pruned networks, it still would've given errors about not being able to create the containers because the container names already exist.
The best solution may be, instead of `builder.py` asking if the user wants to stop all running containers, it should ask:
```
? Do you want to stop and remove all running exrproxy-env containers?  (Y/n)
```
On a "yes" response, it should then stop *and* remove all exrproxy-env containers before proceeding to ask about pruning images, networks, and volumes.

2022-03-09 23:07 UTC, pom11 commented
i think we should do one step for everything related to docker env like 
`? Do you want to stop and remove all running exrproxy-env containers/networks/volumes/images?  (Y/n)`

2022-03-09 23:12 UTC, ConanMishler commented
> i think we should do one step for everything related to docker env like
> `? Do you want to stop and remove all exrproxy-env related containers/networks/volumes/images? (Y/n)`

Sounds good to me, but we should definitely include the reassuring statement: "(Will not delete synced blockchain data.)"

2022-03-09 23:26 UTC, ConanMishler commented
- [ ] 28. Great idea to add better logging to docker services by inserting these lines in `docker-compose.yml`:
```
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```
However, I have been unsuccessful at configuring docker on VPS4 to use `"log-driver": "json-file"` in spite of my best efforts. I created the file, `/etc/docker/daemon.json` with these contents:
```
{
  "log-driver": "json-file"
}
```
Then I restarted docker, but those new logging lines in `docker-compose.yml` are still giving me errors like:
```
ERROR: for 8b6acaff7350_exrproxy-env_avax_1  Cannot create container for service avax: json: cannot unmarshal number into Go struct field LogConfig.HostConfig.LogConfig.Config of type string
```
More importantly, even if/when I succeed in setting docker log-driver to `"json-file"` on my VPS4, it may not be set that way on other systems by default. According to the docker docs, "The default logging driver is json-file." So I'm not sure what the issue is. I just know that attempts to deploy the `docker-compose.yml` currently generated by the latest `builder.py` give me errors like the above.

2022-03-10 12:51 UTC, tryiou commented
Suggestion:

Allow user to set _url_ or  _ip,_ at this step:
`? Press Enter to confirm external IP address or type a new one:  `

Right now it gather external ipv4, and if we try to input url to replace, it still choose the ipv4 detected.

2022-03-10 14:28 UTC, ConanMishler commented
> Suggestion:
> 
> Allow user to set _url_ or _ip,_ at this step: `? Press Enter to confirm external IP address or type a new one: `
> 
> Right now it gather external ipv4, and if we try to input url to replace, it still choose the ipv4 detected.

- [ ] 29. If I understood @tryiou 's Discord comments correctly, it seems `builder.py` is actually accepting the URL he enters and using it correctly internally, but just displaying the public IP it fetched instead of the URL he entered.
Another discovery he made was that the URL he entered gets passed to `avalanchego` via the `--public-ip=<IP>` param. This causes `avalanchego` to crash, so we need to make sure the *real* public IP of the machine is passed to `avalanchego`, even if the user enters a URL instead of an IP address.

2022-03-12 22:44 UTC, pom11 commented
commit without point 1 and 30

2022-03-13 03:49 UTC, ConanMishler commented
Great work! It's getting more refined with each iteration!
Just a few little points:

- [ ] 32. There is no option to change `/snode` for *all* coins by typing the new default data mount directory just once. For example, if I want to store all locally hosted coins/services in a data mount directory called `/bigdrive`, I have to type, `/bigdrive` for every coin/service I will support. It will be much more user friendly to ask at the beginning if the user would like to change the default data mount directory from `/snode` to something else. Then all the individual coin/service data mount dir queries can present `/bigdrive` as the default data mount directory, and ask the user if they want to change it for each individual coin/service.

- [ ] 33. After specifying custom data mount directories for some coins during the first run of `builder.py`, it failed to remember my choices for custom data mount directories for those coins on the second run of `builder.py`.

- [ ] 34. A new version of `avaplatform/avalanchego:latest` (v1.7.7) was released on docker hub since I last deployed my stack via `docker-compose up`. But `docker-compose` wasn't aware of the new version on docker hub, so it didn't update my local `avaplatform/avalanchego:latest` image with the latest image from docker hub. I think we just need to add one `docker-compose pull` line to `deploy.sh`:
```
#!/bin/bash
docker-compose pull
docker-compose --env-file .env -f "docker-compose.yml" up -d --build
```

- [ ] 35. `builder.py` didn't check if a `data mount dir` I entered to replace /snode was specified as an absolute path (i.e. beginning with "/"). It gave no error when I entered the following:
```
? Press enter to confirm /snode for LTC or type a new absolut path:  bigdir
 Directory  Available  Required 
 bigdir     33 GB      75 GB    
```

- [ ] 36. `docker-compose down` used to stop all containers in parallel (in different threads). Current `builder.py` stops containers serially, which will take quite some time if an snode happens to have 20+ containers running, considering each container typically takes 5-10 seconds to stop.

- [ ] 37. `builder.py` currently asks:  
```
? Press enter to confirm /snode for ETH or type a new absolut path:  
```
before asking if I want to deploy ETH locally or externally. This could confuse the user because the question is not relevant for those wanting to deploy ETH externally. (Similarly w/ AVAX)

- [ ] 38. On a server which already has a fully synced AVAX node, `builder.py` currently asks:  
```
? Press enter to confirm /snode for AVAX or type a new absolut path:  
 Directory  Available  Required 
 /snode     316 GB     400 GB   
```
This report of *Available* vs *Required* space could be confusing in this case where the blockchain is already fully synced. It makes it look like there is not enough space on /snode to support AVAX. But the truth is that 0 GB additional space is actually what is required if /snode/AVAX data dir already exists and is full of blockchain data.

- [ ] 39. To get `docker-compose up` to to run, I still have to manually remove from `docker-compose.yml` all the special logging entries:
```
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```
I vote we take those out of `docker-compose.yml` until `builder.sh` can guarantee the docker environment can handle that fancy logging.

- [ ] 40. Got a weird errors about `invalid config in YAML` (--branchpath param was not passed):
```
conan@VPS2:~/exrproxy-env$ ./builder.py 
Loading File: autobuild/sources.yaml
Loading File: .known_hosts
                          Hardware  Size  
 🔀 EXRPROXY-ENV BUILDER  DISK      33 GB 
                          RAM       16 GB 
                          CPU       6     

Checking docker daemon...
Docker found
Checking running containers
Found PUBLIC_IP=185.217.127.108
? Press Enter to confirm external IP address or type a new one:  
Saved PUBLIC_IP=185.217.127.108
Found SN_NAME=bermuda
? Press Enter to confirm Servicenode Name or type a new one:  
Saved SN_NAME=bermuda
Found SN_KEY=Pnvk9V4AtwKDkfwJACSXWbdcZjmVEjUA3M4zpmk575V4p2xBPEH4
? Press Enter to confirm Servicenode Private Key or type a new one:  
Saved SN_KEY=Pnvk9V4AtwKDkfwJACSXWbdcZjmVEjUA3M4zpmk575V4p2xBPEH4
Found SN_ADDRESS=BZjYp4p4qZqVqLiFouqBfUTB8vHJGJoWR4
? Press Enter to confirm Servicenode Address or type a new one:  
Saved SN_ADDRESS=BZjYp4p4qZqVqLiFouqBfUTB8vHJGJoWR4
Found RPC_USER=loving-benz
? Press Enter to confirm Servicenode Username or type a new one:  
Saved RPC_USER=loving-benz
Found RPC_PASSWORD=getup-tingle-unkind-wiry-pummel-john
? Press Enter to confirm Servicenode Password or type a new one:  
Saved RPC_PASSWORD=getup-tingle-unkind-wiry-pummel-john
? Press enter to confirm /snode for XR_PROXY or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      1 GB     
? Press enter to confirm /snode for SNODE or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      5 GB     
? Press enter for 35USD tier1 amount or type a new USD price:  
? Press enter for 200USD tier2 amount or type a new USD price:  
? Press enter for 20% aBLOCK discount or type a new discount (e.g. 15 for 15% aBLOCK discount):  
? Press enter for 0% aaBLOCK discount or type a new discount (e.g. 15 for 15% aaBLOCK discount):  
? Press enter to confirm /snode for PAYMENT or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      None GB  
? What chains do you wish to support?  done (11 selections)
? Press enter to confirm /snode for BTC or type a new absolut path:  /bigdrive
 Directory  Available  Required 
 /bigdrive  33 GB      500 GB   
? Press enter to confirm /snode for DASH or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      35 GB    
? Press enter to confirm /snode for DGB or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      30 GB    
? Press enter to confirm /snode for LTC or type a new absolut path:  /bigdrive
 Directory  Available  Required 
 /bigdrive  33 GB      75 GB    
? Press enter to confirm /snode for PIVX or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      23 GB    
? Press enter to confirm /snode for SYS or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      4 GB     
? Press enter to confirm /snode for LBC or type a new absolut path:  /bigdrive
 Directory  Available  Required 
 /bigdrive  33 GB      150 GB   
? Press enter to confirm /snode for MUE or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      6 GB     
? Press enter to confirm /snode for PHR or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      7 GB     
? Press enter to confirm /snode for RVN or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      27 GB    
? Press enter to confirm /snode for GBX or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      3 GB     
? What EVM chains do you wish to support?  done (2 selections)
? Press enter to confirm /snode for ETH or type a new absolut path:  /superbigdrive
 Directory       Available  Required 
 /superbigdrive  33 GB      10000 GB 
? Select one host for ETH  98.215.160.113
? Press enter to confirm /snode for AVAX or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      400 GB   
? Press enter to use AVAX internally or type external IP Address:  
Wrote .known_hosts
? Do you wish to support HYDRA?  Yes
? Select EVM chains to attach HYDRA to:  done (2 selections)
? Do you wish to support FREE access to HYDRA?  No
? Do you wish to support XQUERY?  No
? Press enter to save config as 13-03-2022-04:24 or enter name:  latest
Wrote inputs_yaml/latest.yaml
Processing custom input...
fetch template for BTC from raw.git
fetch template for DASH from raw.git
fetch template for DGB from raw.gi [...]

2022-03-13 07:27 UTC, pom11 commented
commit for 39 and 40

2022-03-13 08:04 UTC, walkjivefly commented
- [ ] 41. Typo: "absolut" should be "absolute".

2022-03-13 09:58 UTC, pom11 commented
36. we have to wait for all containers to be stopped so that we can remove/prune them. `stop` function has a timeout parameter until it sends kill signal to the container, the default one is 10 seconds. for first AwesomeBuilder iteration i think is fine if we dont use threading.

2022-03-13 13:59 UTC, ConanMishler commented
Thinking more about the flow of the current `builder.py`, I realize it doesn't really fulfill the intention behind *point 16 (Improved)*. The intention was that the user should be given information about the HW requirements of services *before* they are asked to choose whether or not to support those services. So, for example, this screen:
![image](https://user-images.githubusercontent.com/72487933/158062764-9ebcc950-0ff8-42c4-8a55-a3e23d4793ba.png)
should look something like this:
```
? What chains do you wish to support?
  *  BTC  (500 GB)
  *  DASH (35 GB)
  *  DGB (30 GB)
 ...
```
Info. about the HW requirements for ETH and AVAX should also be displayed *before* the user has to choose whether they want to support them.

2022-03-13 14:17 UTC, ConanMishler commented
- [ ] 42. Thinking more about Info. displayed about Available disk space...

```
? Press enter to confirm /snode for DASH or type a new absolut path:  
 Directory  Available  Required 
 /snode     33 GB      35 GB    
```
It would actually be much more helpful to display Info. about available space on /snode *before* the user has to choose whether or not to enter a new absolute path.
Actually, to simplify things for now, I wouldn't even bother to display any Info. about *Available* during the process of selecting alternate data mount directories. I would simply add general Info at the very beginning about available disk space on all mounted directories where there is more than 5 GB of free space (Info gathered from `df -h`). Currently, it displays this at the beginning:
```
                                                 Hardware  Size  
 🔀 EXRPROXY-ENV BUILDER  DISK      33 GB 
                                                     RAM       16 GB 
                                                     CPU       6     
```
I'd change this a bit to display the *Available* space on each mounted directory (as per `df -h`) where there is > 5 GB of free space, then make it clear that's the *Available* space for on each of those, not the *Size* of the mounted dir. (Currently, the *Available* space is displayed, though it's listed as *Size*. Also, currently only the available space on the `/` mounted dir is displayed. There could be large spaces mounted on other drives as well.)

2022-03-13 23:07 UTC, ConanMishler commented
> commit for 35, 39 and 40
> 
> 35. `builder.py` checks if the typed dir exists or not and if it doesnt it checks available space for root parent dir of it.
>     if typed `/home/bigdir` and `bigdir` doesnt exist, the available free space displayed is for `/home`; same for `bigdir` -> `/`

- [ ] 35 (continued). Yes, I noticed that's what it's doing, which makes sense. However, my concern was not about the way it checks and reports available space. My concern was that the query asks the user to *type a new absolut path*. I entered a path which was *not* an absolute path (`bigdrive`) and it did *not* give me an error. So is it true then that the user is *not* actually required to specify an absolute path? I think one of two things should be done:

1. If the user is indeed required to specify an absolute path, as the current query seems to imply, then it should give an error and prompt the user again if the user specifies a path which is not absolute (i.e. if the user specifies a path which does not begin with `/`).
2. If the user is allowed to specify a relative path in response to these queries, then the query should say something like,
```
? Press enter to confirm /snode for LTC or type a new absolute path, or a non-absolute path relative to current directory:
```
This issue is not a big deal, but it's super easy to make this change, and it makes the app more bozo-proof.

2022-03-14 15:55 UTC, ConanMishler commented
> Further task will not be taken into consideration in current PR

Agreed. After tasks are completed through 42, it will be ready for release.

2022-03-15 11:47 UTC, pom11 commented
commit done without 1 & 30

2022-03-15 20:11 UTC, ConanMishler commented
- [ ] 42 (continued):  I like this idea of displaying the amount of space already occupied in the *Existing dir*:
![image](https://user-images.githubusercontent.com/72487933/158462823-a1c6889c-a766-4569-829e-c78c3e7b4c2c.png)
However, in this test I did on VPS2, `/snode/AVAX` exists and occupies 324 GB. Shouldn't the *Existing dir* number for AVAX display 324 GB here (instead of 0 GB)?

2022-03-15 20:33 UTC, ConanMishler commented
- [ ] 42 (continued):  Overall, it's looking *very* good. Nearly ready for release, I think. There is one more minor thing we could improve at these two points in the query process:
![image](https://user-images.githubusercontent.com/72487933/158466437-49cafd6d-7647-46d0-be6c-a4f0b0ae2e37.png)
![image](https://user-images.githubusercontent.com/72487933/158466500-6087b4ea-5d4f-4fb4-963d-ac127434515c.png)
In these two queries, it displays HW requirement info, but it's not really needed in these queries because the HW requirements for those resources were already displayed earlier when the user decided to support those services. In fact, it could be confusing to the user to display the HW Reqs again here. They might think, "Will I need double those requirements?" It could be especially confusing if one or more of the services was already selected to be hosted externally, as was done for ETH in this example. I suggest we simply don't display any HW requirements on these queries.

2022-03-16 22:08 UTC, ConanMishler commented
- [ ] Last remaining tasks:
TODO 
- persistent IPs
- check disk usage under sudo

2022-03-17 03:21 UTC, ConanMishler commented
- [ ] 43. I hesitate to write "43" because I agreed it would be ready for release after 1-42 were complete. However, something broke with the addition of `.cache`.  What broke? The default responses for all the ticks became *NO* for someone running `builder` for the first time, when `.cache` is still empty. @tryiou mentioned this issue also in Discord. I'm pretty sure we want all the tick responses to be *YES* when `.cache` is completely empty.

2022-03-17 06:43 UTC, pom11 commented
with .cache feature the default configuration is a simple snode one. pressing Enter for all inquiries results in classic snode config.

2022-03-29 21:56 UTC, ConanMishler approved these changes
Well, it didn't take long to get *this* PR approved! 🤣

2022-03-30 07:04 UTC, merged